# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-02 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askmeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionlike',
            name='compose_key',
            field=models.CharField(default=b'None0', max_length=70, unique=True),
        ),
    ]
