# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-03 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askmeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='questionlikes',
            field=models.ManyToManyField(to='askmeapp.QuestionLike'),
        ),
    ]
