# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askmeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='text',
            field=models.CharField(max_length=50, verbose_name=b'Tag'),
        ),
    ]
