# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 15:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('askmeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': '\u0410\u0432\u0442\u043e\u0440', 'verbose_name_plural': '\u0410\u0432\u0442\u043e\u0440\u044b'},
        ),
    ]
