# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-04 22:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askmeapp', '0002_auto_20161203_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
