# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askmeapp', '0005_auto_20161117_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(upload_to=b'/uploads'),
        ),
    ]
