# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askmeapp', '0006_auto_20161117_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='owner_rating',
        ),
        migrations.RemoveField(
            model_name='question',
            name='owner_rating',
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(upload_to=b'uploads'),
        ),
    ]
