# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askmeapp', '0008_auto_20161117_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default=b'uploads/user_avatar.jpeg', upload_to=b'uploads'),
        ),
    ]
