# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-19 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askmeapp', '0009_auto_20161117_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='rating',
        ),
        migrations.AddField(
            model_name='like',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
