# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-20 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askmeapp', '0014_auto_20161120_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='style_number',
            field=models.IntegerField(default=1),
        ),
    ]
